server:
  port: 8120 

spring:
  profiles:
    active: dev 
  application:
    name: service-oss
  #spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
    nacos:
      discovery:
        server-addr: localhost:8848 

aliyun:
  oss:
    endpoint: oss-us-east-1.aliyuncs.com
    keyid: <access-key>
    keysecret: <acess-key-secret>
    bucketname: ourclassroom-file
