server:
  port: 8140 # service port

spring:
  profiles:
    active: dev
  application:
    name: service-cms # the name of the service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    password:
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0

  datasource: # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ourclassroom_cms?serverTimezone=America/New_York
    username: root
    password: root
  #spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/New_York

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/ourclassroom/ourclassroom/service/cms/mapper/xml/*.xml
  mapperLocations: classpath:**/xml/*.xml

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

feign:
  sentinel:
    enabled: true