server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: <your-access-key>
      secret-key: <your-access-secrete>
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: ourclassroom
